services:
  - docker

install:
  - echo "nothing needs to be installed"

before_script:
  - echo "no tests"

script:
  - docker --version  # prints the version of logging
  - docker build -t udagram-reverseproxy .
  - docker tag udagram-reverseproxy abheist/udagram-reverseproxy

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push abheist/udagram-reverseproxy